exp_name = "plots_2k"
verbose = 1 # 0 : print everything 1 : print only summary : 2 : minimal printing
max_events = 100
data_path = "data/ntuple_v3_2000k.root"
export_data_path = "data/ntuple_v3_2000k.npy"
load_from_export_data_path = True # speedup x2000
tree_name = "SimpleJet"
input_size = 5
output_size = 3
hidden_size = output_size
dropout = 0.5
lr = 0.001
n_epochs = 20
batch_size = 20
data_verbosity = 2
dev_size = 0.1
test_size = 0.2
results_path = "results/test_set_results.txt"